# Generated by Django 4.1.7 on 2023-02-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="location",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
