# Generated by Django 4.1.7 on 2023-02-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_delete_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "biweekly_schedule",
                    models.CharField(
                        choices=[
                            ("A", "Biweekly Schedule A"),
                            ("B", "Biweekly Schedule B"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
