# Generated by Django 4.1.7 on 2023-02-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_delete_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
